-- SQL script to build the schema for the driving_leaderboard table in Supabase

CREATE TABLE IF NOT EXISTS driving_leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT NOT NULL CHECK (char_length(player_name) <= 20),
    score INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add an index on the score column to optimize sorting queries (descending order)
CREATE INDEX IF NOT EXISTS idx_driving_leaderboard_score ON driving_leaderboard (score DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE driving_leaderboard ENABLE ROW LEVEL SECURITY;

-- Clean up existing policies if they exist to avoid duplication errors
DROP POLICY IF EXISTS "Allow public read access" ON driving_leaderboard;
DROP POLICY IF EXISTS "Allow public insert access" ON driving_leaderboard;

-- Create policy to allow anyone to read scores
CREATE POLICY "Allow public read access" ON driving_leaderboard
    FOR SELECT TO anon USING (true);

-- Create policy to allow anyone to insert a new score
CREATE POLICY "Allow public insert access" ON driving_leaderboard
    FOR INSERT TO anon WITH CHECK (true);


