-- SQL script to build the schema for the driving_leaderboard table in Supabase

CREATE TABLE driving_leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT NOT NULL CHECK (char_length(player_name) <= 20),
    score INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add an index on the score column to optimize sorting queries (descending order)
CREATE INDEX idx_driving_leaderboard_score ON driving_leaderboard (score DESC);

-- Example row insertion for testing
-- INSERT INTO driving_leaderboard (player_name, score) VALUES ('Speedster', 1500);
